# Generated by Django 4.1 on 2022-09-14 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mvt1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('edad', models.DateField()),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
    ]
